In [122]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold, cross_validate, GridSearchCV
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

In [123]:
df = pd.read_csv(r"C:\Users\Roman Shypka\OneDrive\Робочий стіл\news_data.csv")

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50030 entries, 0 to 50029
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50030 non-null  int64
 1   Text        50027 non-null  object
 2   Label       50030 non-null  bool
dtypes: bool(1), int64(1), object(1)
memory usage: 830.7+ KB

In [125]:
## clean data from diferent http
df["Text"] = df["Text"].astype(str).str.replace(r'https?://\S+|www\.\S+|bit\.ly\S+',"", regex=True).str.strip()

In [126]:
df[df["Text"].str.contains("https",na=False)]

       Unnamed: 0                                               Text  Label
12115       12115  7 найцікавіших текстів ТСНua за тижденьСпалах ...   True

In [127]:
# conversion from bool type in int 
le = LabelEncoder()
df["Label"] = le.fit_transform(df["Label"])

In [128]:
df.head(5)

   Unnamed: 0                                               Text  Label
0           0  В Україні запустять механізм перевірки наявнос...      1
1           1  У Флориді через рекордно низькі температури на...      1
2           2  ТГ-канал FUCKТИ повідомив про бомбардування Ки...      0
3           3  Окупований Маріуполь не здається. Юнак вийшов ...      1
4           4  Чернігів, Кропивницький і область — повітряна ...      1

In [129]:
df["Label"].value_counts()

Label
1    48006
0     2024
Name: count, dtype: int64

## create balance data

In [130]:
fakes = df[df["Label"] == 0]

In [131]:
trues = df[df["Label"] == 1 ].sample(n=7000,random_state=42)

In [141]:
df_balanced = pd.concat([trues,fakes]).sample(frac=1,random_state=42).reset_index(drop=True)
df_balanced["Label"].value_counts()

Label
1    7000
0    2024
Name: count, dtype: int64

In [133]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2),max_df=0.7)

## Train

In [94]:
X = (df_balanced["Text"])
y = df_balanced["Label"]

In [95]:
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [96]:
X_train = vectorizer.fit_transform(X_train_raw)
X_test = vectorizer.transform(X_test_raw)

In [97]:
metrics = ["accuracy","precision","recall","f1"]

In [99]:
GridSearchCV

sklearn.model_selection._search.GridSearchCV

In [100]:
model = KNeighborsClassifier(n_neighbors=21,metric="cosine")
model.fit(X_train,y_train)

KNeighborsClassifier(metric='cosine', n_neighbors=21)

In [101]:
predictions = model.predict(X_test)

In [85]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(metric='cosine'),
             param_grid={'n_neighbors': [3, 5, 11, 21, 41, 61, 81, 85]},
             scoring='f1')

## Metrics

In [102]:
skf = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)

In [103]:
print(classification_report(y_test, predictions , target_names = ["Fake(0)","True(1)"]))

              precision    recall  f1-score   support

     Fake(0)       0.94      0.79      0.86       437
     True(1)       0.94      0.98      0.96      1368

    accuracy                           0.94      1805
   macro avg       0.94      0.89      0.91      1805
weighted avg       0.94      0.94      0.93      1805

In [137]:
pd.Series(predictions).value_counts()

1    1440
0     365
Name: count, dtype: int64

In [138]:
y_train.value_counts()

Label
1    5632
0    1587
Name: count, dtype: int64

In [ ]:
# 1. Retrieve all features (vocabulary) learned by the vectorizer
feature_names = vectorizer.get_feature_names_out()

# 2. Extract weights (coefficients) from the trained logistic regression model
# model.coef_[0] contains the importance values for each feature
coefficients = model.coef_[0]

# 3. Pair each feature name with its corresponding coefficient
word_weights = list(zip(feature_names, coefficients))

# 4. Sort the list by weights (from the most negative to the most positive)
sorted_words = sorted(word_weights, key=lambda x: x[1])

# --- DISPLAYING THE RESULTS ---

print("🛑 TOP-20 words that strongly indicate 'FAKE' (pulling towards 0):")
print("-" * 50)
# Slice the first 20 words with the lowest (negative) coefficients
for word, weight in sorted_words[:20]:
    print(f"{word}: {weight:.4f}")

print("\n ✅ TOP-20 words that strongly indicate 'TRUE' (pulling towards 1):")
print("-" * 50)
# Slice the last 20 words with the highest (positive) coefficients and reverse them
for word, weight in reversed(sorted_words[-20:]):
    print(f"{word}: {weight:.4f}")

In [49]:
param_grid = {"n_neighbors": [3,5,11,21,41,61,81,85]}
grid = GridSearchCV(KNeighborsClassifier(metric='cosine'),param_grid,cv=5,scoring="f1",)
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(metric='cosine'),
             param_grid={'n_neighbors': [3, 5, 11, 21, 41, 61, 81, 85]},
             scoring='f1')

In [71]:
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("knn", KNeighborsClassifier(metric="cosine"))
     ])

param_grid = {
    "tfidf__ngram_range": [(1, 1 ) , (1 , 2)],
    "tfidf__max_df": [0.5,0.6,0.7, 0.9 , 1.0], 
    "knn__n_neighbors":[11, 21 , 41]}

grid_pipeline = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="recall"
)

grid_pipeline.fit(X_train_raw, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('knn',
                                        KNeighborsClassifier(metric='cosine'))]),
             param_grid={'knn__n_neighbors': [11, 21, 41],
                         'tfidf__max_df': [0.5, 0.6, 0.7, 0.9, 1.0],
                         'tfidf__ngram_range': [(1, 1), (1, 2)]},
             scoring='recall')

In [72]:
pred_grid = grid_pipeline.predict(X_test_raw)
print(classification_report(y_test, pred_grid, target_names=["Fake(0)", "True(1)"]))

              precision    recall  f1-score   support

     Fake(0)       0.98      0.75      0.85       437
     True(1)       0.93      0.99      0.96      1368

    accuracy                           0.94      1805
   macro avg       0.95      0.87      0.90      1805
weighted avg       0.94      0.94      0.93      1805